### PR TITLE
Avoid conflicting trusted certificates with SmartID

### PR DESCRIPTION
**Pull request by cbxp**
use a more unique name for trusted_certificates to avoid conflict with SmartID library that has a file with the same name

### CODE REVIEW

**Comment by cbxp** [comment]
This probably fixes #33

**Comment by aasaru** [comment]
Thanks for bug report.

The plan is to fade out certificates hard-coded into the library so that whoever uses the mobile-id/smart-id libraries should always keep own trust store (or list of trusted certificates) on own code base. So the hard-coded trust store will be completely removed in the next release.

**Comment by aasaru** [comment]
LGTM. we can create a bugfix release 1.2.1 out of this.

**Comment by cbxp** [comment]
Please do!

**Pull request merged**
